dist: bionic
language: ruby
cache: bundler

rvm:
  - ruby-head
  - 2.7.1
  - 2.6.6
  - 2.5.8
  - 2.4.10

gemfile:
  - gemfiles/openssl_head.gemfile
  - gemfiles/openssl_2_1.gemfile
  - gemfiles/openssl_2_0.gemfile
  - gemfiles/openssl_default.gemfile

before_install: gem install bundler -v '~> 2.0'

matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
    - gemfile: gemfiles/openssl_head.gemfile
