sudo: false
language: ruby

os:
  - linux
  - osx

rvm:
  - 2.6.0-preview2
  - 2.5.1
  - 2.4.4

before_install:
  - gem install bundler -v 1.16.2
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./script/setup-linux; else ./script/setup-osx; fi

matrix:
  fast_finish: true
  allow_failures:
    - rvm: 2.6.0-preview2
